# Haskell Stack configuration
#
# See https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-8.4

packages:
    - ./modules/example-lib
    - ./modules/example-app

nix:
    enable: true
    pure: true
    packages: []
    shell-file: modules/stack/stack.nix

flags: {}
extra-package-dbs: []
